# Generated by Django 3.0.7 on 2024-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240214_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_point',
            field=models.IntegerField(default=0),
        ),
    ]
