# Generated by Django 3.0.7 on 2024-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_reorder_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
