# Generated by Django 3.0.7 on 2024-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('name', 'sub_category')},
        ),
    ]
