# Generated by Django 3.0.7 on 2024-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240218_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_sales_value',
            field=models.IntegerField(default=0),
        ),
    ]
