# Generated by Django 3.0.7 on 2024-02-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_saleitem_total_sales_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
